### ISSUE TITLE
"Pure-Data" website link in Readme.md it is wrong

### ISSUE THREAD

**Issue by zohozer** [FlachyJoe/FCPDWorkbench#27]
On the "Readme.md" file it is an error to the link to the  "Pure-Data" website.

https://puredata.info

Needs to be changed from: 
`The [FCPD](https://github.com/FlachyJoe/FCPD) workbench bridges [FreeCAD](https://github.com/FreeCAD/FreeCAD) (FC), an open source CAD program with [Pure-Data](-data/pure-data) (PD), a real-time computer music system.`

to:

`The [FCPD](https://github.com/FlachyJoe/FCPD) workbench bridges [FreeCAD](https://github.com/FreeCAD/FreeCAD) (FC), an open source CAD program with [Pure-Data](https://puredata.info) (PD), a real-time computer music system.`

**Comment by FlachyJoe** [comment]
Fixed b7cee9f
Thank you !
