### ISSUE TITLE
How do you install pure-data list-abs ?

### ISSUE THREAD

**Issue by WillAdams** [FlachyJoe/FCPDWorkbench#28]
When I go to:

https://pure-data.svn.sourceforge.net/svnroot/pure-data/trunk/abstractions/footils/list-abs

I get:

Not Found
The requested URL /svnroot/pure-data/trunk/abstractions/footils/list-abs was not found on this server.

**Comment by FlachyJoe** [comment]
Hi,
- on linux system, you can find list-abs in your package manager: `apt install pd-list-abs`
- Purr-Data and PdL2Ork already include list-abs.
- on other case you can use the _Help->Find Externals_ menu or the [deken website](https://deken.puredata.info/search.html?libraries=list-abs)

**Comment by FlachyJoe** [comment]
Hi @WillAdams ,
any feedback or can I close this issue ?

**Comment by WillAdams** [comment]
Yes, I haven't had occasion to experiment w/ it (doing this on a Linux box I don't use often), but I'm sure that what you described will work.
